### ISSUE TITLE
Reading /etc/spmagent/conf it not always working

### ISSUE THREAD

**Issue by otisg** [sematext/spm-agent-mongodb#1]
It looks like entries in /etc/spmagent/conf are sometimes ignored, like the config is not read.

**Comment by megastef** [comment]
Fixed in 1.29.12 https://github.com/sematext/spm-agent-mongodb/commit/0272d80d78ced351849b9617b82a9b66769ca977 

The problem was the ini file format, depending on space/tabs/line breaks the sub-keys moved to the wrong section. This happened to the key mongodb.url with the configuration generated by the setup script. Since the mentioned commit, the setup script uses JSON format for the configuration file.
